services:
  - type: web
    name: kulturama
    runtime: node
    buildCommand: npm run install:all && npm run build && npm run seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@malibrairie.ci
      - key: ADMIN_PASSWORD
        value: Admin@2026!
